// 전국 골프장 디렉토리 (문화체육관광부_전국 골프장 현황, 2026-05-28 기준(파일명과 무관), 541곳)
// name/region/holes/type/address. 홀별 PAR는 lib/coursesDb.js에서 별도 관리.
export const COURSE_DIRECTORY = [
  {"name": "라데나골프클럽", "region": "강원", "holes": 27, "type": "회원제", "address": "춘천시 신동면 칠전동길 72"},
  {"name": "엘리시안 강촌컨트리클럽", "region": "강원", "holes": 27, "type": "회원제", "address": "춘천시 남산면 북한강변길 688"},
  {"name": "제이드팰리스 골프클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "춘천시 남산면 경춘로 212-30"},
  {"name": "남춘천컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "춘천시 신동면 오봉길 156"},
  {"name": "휘슬링락컨트리클럽", "region": "강원", "holes": 27, "type": "회원제", "address": "춘천시 남산면 동촌로 501"},
  {"name": "오너스골프클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "춘천시 남산면 동촌로 667"},
  {"name": "세레니티강촌컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "춘천시 남면 소주고개로 145-10"},
  {"name": "더플레이어스 골프클럽", "region": "강원", "holes": 27, "type": "대중제", "address": "춘천시 동산면 새술막길 438"},
  {"name": "스프링베일리조트", "region": "강원", "holes": 9, "type": "대중제", "address": "춘천시 동면 금베이길 93-27"},
  {"name": "로드힐스골프클럽", "region": "강원", "holes": 27, "type": "대중제", "address": "춘천시 동산면 종자리로 148-16"},
  {"name": "라비에벨컨트리클럽", "region": "강원", "holes": 36, "type": "대중제", "address": "춘천시 동산면 종자리로 436"},
  {"name": "베어크리크 춘천", "region": "강원", "holes": 18, "type": "대중제", "address": "춘천시 신동면 김유정로 730"},
  {"name": "오크밸리회원제골프장", "region": "강원", "holes": 36, "type": "회원제", "address": "원주시 지정면 오크밸리1길 66"},
  {"name": "월송리 컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "원주시 지정면 오크밸리2길 250"},
  {"name": "Oak Hills컨트리클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "원주시 지정면 오크밸리2길 58"},
  {"name": "성문안 컨트리클럽", "region": "강원", "holes": 18, "type": "비회원제", "address": "원주시 지정면 월송석화로 431"},
  {"name": "센추리21컨트리클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "원주시 문막읍 궁말길 193"},
  {"name": "센추리21컨트리클럽Ⅱ", "region": "강원", "holes": 18, "type": "대중제", "address": "원주시 문막읍 궁말길 193"},
  {"name": "센추리21퍼블릭", "region": "강원", "holes": 9, "type": "대중제", "address": "원주시 문막읍 궁말길 193"},
  {"name": "파크밸리골프클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "원주시 소초면 바우실길 281"},
  {"name": "동서울레스피아", "region": "강원", "holes": 9, "type": "대중제", "address": "원주시 지정면 신평석화로 236"},
  {"name": "인터불고원주골프클럽", "region": "강원", "holes": 9, "type": "비회원제", "address": "원주시 동부순환로 200(반곡동)"},
  {"name": "오로라 골프 앤 리조트", "region": "강원", "holes": 18, "type": "대중제", "address": "원주시 신림면 구학산로 1520"},
  {"name": "샌드파인골프클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "강릉시 저동등길 53(저동)"},
  {"name": "메이플비치골프&리조트", "region": "강원", "holes": 18, "type": "대중제", "address": "강릉시 강동면 풍호길 300-78"},
  {"name": "O2리조트 골프장", "region": "강원", "holes": 18, "type": "대중제", "address": "태백시 서학로 861"},
  {"name": "O2리조트 퍼블릭골프장", "region": "강원", "holes": 9, "type": "대중제", "address": "태백시 서학로 861"},
  {"name": "설악프라자컨트리클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "속초시 미시령로2983번길 56-20"},
  {"name": "영랑호컨트리클럽", "region": "강원", "holes": 9, "type": "대중제", "address": "속초시 영랑호반길 170"},
  {"name": "파인밸리컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "삼척시 근덕면 미근로 1629"},
  {"name": "블랙밸리컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "삼척시 도계읍 도상로 307-84"},
  {"name": "소노펠리체 컨트리클럽 비발디파크 웨스트", "region": "강원", "holes": 18, "type": "대중제", "address": "홍천군 서면 한치골길 200"},
  {"name": "소노펠리체 컨트리클럽 비발디파크 마운틴", "region": "강원", "holes": 9, "type": "대중제", "address": "홍천군 서면 한치골길 264"},
  {"name": "소노펠리체 컨트리클럽 비발디파크 이스트", "region": "강원", "holes": 18, "type": "대중제", "address": "홍천군 서면 한치골길 541-123"},
  {"name": "비콘힐스골프클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "홍천군 홍천읍 높은터로 533"},
  {"name": "힐드로사이컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "홍천군 남면 한서로 2840"},
  {"name": "클럽모우골프 &라이프스타일", "region": "강원", "holes": 27, "type": "대중제", "address": "홍천군 서면 장락동길 111"},
  {"name": "세이지우드CC홍천", "region": "강원", "holes": 27, "type": "비회원제", "address": "홍천군 두촌면 광석로 898-160"},
  {"name": "샤인데일골프&리조트", "region": "강원", "holes": 27, "type": "대중제", "address": "홍천군 서면 한서로 247-156"},
  {"name": "카스카디아 골프클럽", "region": "강원", "holes": 27, "type": "비회원제", "address": "홍천군 북방면 팔봉산로 1759"},
  {"name": "웰리힐리컨트리클럽", "region": "강원", "holes": 36, "type": "회원제", "address": "횡성군 둔내면 고원로 451"},
  {"name": "웰리힐리퍼블릭", "region": "강원", "holes": 10, "type": "비회원제", "address": "횡성군 둔내면 고원로 451"},
  {"name": "동원썬밸리컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "횡성군 서원면 서원서로339번길 90"},
  {"name": "알프스대영컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "횡성군 우천면 한우로 1295"},
  {"name": "벨라스톤컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "횡성군 서원면 옥계9길 124"},
  {"name": "올데이 옥스필드", "region": "강원", "holes": 18, "type": "대중제", "address": "횡성군 서원면 경강로 유현6길 28"},
  {"name": "벨라45 오너스 컨트리클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "횡성군 서원면 창촌리 산132"},
  {"name": "벨라45마스터스 컨트리클럽", "region": "강원", "holes": 27, "type": "대중제", "address": "횡성군 서원면 창촌리 산124"},
  {"name": "동강시스타 골프장", "region": "강원", "holes": 18, "type": "대중제", "address": "영월군 영월읍 사지막길 160"},
  {"name": "용평리조트골프클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "평창군 대관령면 올림픽로 715"},
  {"name": "용평버치힐골프클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "평창군 대관령면 올림픽로 715"},
  {"name": "용평리조트대중골프장", "region": "강원", "holes": 9, "type": "대중제", "address": "평창군 대관령면 올림픽로 715"},
  {"name": "휘닉스 컨트리클럽", "region": "강원", "holes": 18, "type": "회원제", "address": "평창군 봉평면 태기로 227-84"},
  {"name": "휘닉스대중골프장", "region": "강원", "holes": 6, "type": "대중제", "address": "평창군 봉평면 태기로 227-84"},
  {"name": "알펜시아컨트리클럽", "region": "강원", "holes": 27, "type": "회원제", "address": "평창군 대관령면 솔봉로 325"},
  {"name": "알펜시아 700골프클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "평창군 대관령면 솔봉로 325"},
  {"name": "하이원컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "정선군 고한읍 고한7길 399"},
  {"name": "에콜리안정선골프장", "region": "강원", "holes": 9, "type": "대중제", "address": "정선군 신동읍 새골길 112-49"},
  {"name": "한탄강컨트리클럽", "region": "강원", "holes": 18, "type": "대중제", "address": "철원군 갈말읍 순담길 59"},
  {"name": "설악썬밸리컨트리클럽", "region": "강원", "holes": 27, "type": "대중제", "address": "고성군 죽왕면 순포로 188"},
  {"name": "소노펠리체 컨트리클럽 델피노", "region": "강원", "holes": 18, "type": "대중제", "address": "고성군 토성면 미시령옛길 1153"},
  {"name": "파인리즈컨트리클럽", "region": "강원", "holes": 27, "type": "대중제", "address": "고성군 토성면 잼버리동로 267"},
  {"name": "설해원", "region": "강원", "holes": 27, "type": "대중제", "address": "양양군 손양면 공항로 230"},
  {"name": "설해원더 레전드 코스", "region": "강원", "holes": 18, "type": "대중제", "address": "양양군 손양면 공항로 230"},
  {"name": "한원컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 처인구 남사읍 전나무골길2번길 94"},
  {"name": "양지파인골프클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 용인시 처인구 양지면 남평로 112"},
  {"name": "수원컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 용인시 기흥구 중부대로 495"},
  {"name": "플라자CC", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 용인시 처인구 남사읍 봉무로 153번길 79"},
  {"name": "태광컨트리클럽(회원제)", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 기흥구 흥덕4로 77"},
  {"name": "태광컨트리클럽(대중제)", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 기흥구 흥덕4로 77"},
  {"name": "한성컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 기흥구 구교동로 151"},
  {"name": "골드컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 용인시 기흥구 기흥단지로 398"},
  {"name": "국가보훈부 88골프장", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 용인시 기흥구 석성로 521번길 169"},
  {"name": "레이크사이드CC(대중제)", "region": "경기", "holes": 36, "type": "대중제", "address": "경기도 용인시 처인구 모현읍 능원로 181"},
  {"name": "레이크사이드CC(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 용인시 처인구 모현읍 능원로 181"},
  {"name": "남부컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 용인시 기흥구 사은로 163"},
  {"name": "신원CC", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 이동읍 이원로 225"},
  {"name": "은화삼컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 용인시 처인구 백옥대로 860-38"},
  {"name": "아시아나컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 용인시 처인구 양지면 양대로 290"},
  {"name": "블루원용인CC(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 용인시 처인구 원삼면 보개원삼로 1534번길 40"},
  {"name": "블루원용인CC(비회원제)", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 처인구 원삼면 보개원삼로 1534번길 40"},
  {"name": "코리아컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 처인구 이동읍 기흥단지로 579"},
  {"name": "코리아대중CC", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 기흥구 기흥단지로 224"},
  {"name": "지산컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 용인시 처인구 원삼면 죽양대로 2000번길 60"},
  {"name": "지산퍼블릭", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 처인구 원삼면 죽양대로 2100번길 60"},
  {"name": "화산컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 용인시 처인구 이동읍 화산로 239"},
  {"name": "한림용인CC", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 용인시 처인구 남사읍 경기동로 628"},
  {"name": "글렌로스 골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 처인구 포곡읍 에버랜드로 562번길 69"},
  {"name": "용인CC", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 처인구 백암면 황새울로 255"},
  {"name": "석천CC", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 용인시 처인구 백암면 황새울로 255"},
  {"name": "써닝포인트 컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 용인시 처인구 백암면 고안로 51번길 205"},
  {"name": "해솔리아 컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 용인시 처인구 이동읍 백자로 369"},
  {"name": "세현CC", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 용인시 처인구 이동읍 백자로 450"},
  {"name": "한양컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 고양시 덕양구 고양대로1643번길 164"},
  {"name": "뉴코리아 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 고양시 덕양구 신원2로 57"},
  {"name": "고양컨트리클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 고양시 덕양구 흥도로 304-23"},
  {"name": "1·2·3 골프장", "region": "경기", "holes": 6, "type": "대중제", "address": "경기도 고양시 덕양구 통일로 43-168"},
  {"name": "올림픽 골프장", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 고양시 덕양구 혜음로 301"},
  {"name": "일산스프링힐스 컨트리클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 고양시 일산동구 산황로 108"},
  {"name": "한양파인컨트리클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 고양시 덕양구 고양대로 1591"},
  {"name": "남서울컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 성남시 분당구 판교백현로 161"},
  {"name": "리베라컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 화성시 중리길 183"},
  {"name": "기흥컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 화성시 풀무골로106번길 244"},
  {"name": "발리오스컨트리클럽(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 화성시 팔탄면 3.1만세로 641-28"},
  {"name": "발리오스컨트리클럽(비회원제)", "region": "경기", "holes": 9, "type": "비회원제", "address": "경기도 화성시 팔탄면 3.1만세로 641-28"},
  {"name": "라비돌컨트리클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 화성시 정남면 세자로 286"},
  {"name": "화성 상록G.C", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 화성시 풀무골로60번길 80"},
  {"name": "화성골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 화성시 남양읍 화성로 1393-27"},
  {"name": "링크나인골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 화성시 마도면 해운로630번길 49"},
  {"name": "양주 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 남양주시 화도읍 북한강로 1525-52"},
  {"name": "광릉CC(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 남양주시 진접읍 팔야로 280"},
  {"name": "광릉CC(비회원제)", "region": "경기", "holes": 6, "type": "대중제", "address": "경기도 남양주시 진접읍 팔야로 280"},
  {"name": "비전힐스CC", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 남양주시 화도읍 마치로 226-220"},
  {"name": "해비치 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 남양주시 화도읍 재재기로 190번길 160"},
  {"name": "남양주CC", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 남양주시 오남읍 진건오남로 516-31"},
  {"name": "더헤븐 컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 안산시 단원구 대선로466(대부남동)"},
  {"name": "제일컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 안산시 상록구 태마당로28(부곡동)"},
  {"name": "솔트베이 골프클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 시흥시 마유로 987 (장곡동)"},
  {"name": "아세코밸리골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 시흥시 마전로 307 (거모동)"},
  {"name": "김포SEASIDE 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 김포시 월곶면 김포대로 2081번길 219"},
  {"name": "서서울 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 파주시 광탄면 혜음로 324"},
  {"name": "서원밸리 골프장", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 파주시 광탄면 서원길 333"},
  {"name": "서원힐스 골프장", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 파주시 광탄면 서원길 333"},
  {"name": "파주 J-Public 골프장", "region": "경기", "holes": 6, "type": "대중제", "address": "경기도 파주시 조리읍 장곡로 100"},
  {"name": "파주컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 파주시 법원읍 화합로 306"},
  {"name": "베스트밸리 골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 파주시 광탄면 장지산로200번길 32-41"},
  {"name": "노스팜 컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 파주시 광탄면 쇠장이길 265"},
  {"name": "스마트KU 골프 파빌리온", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 파주시 법원읍 보광로 1616"},
  {"name": "타이거CC 골프장", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 파주시 법원읍 술이홀로 1803"},
  {"name": "남촌컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 광주시 곤지암읍 부항길 135-38"},
  {"name": "이스트밸리CC", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 광주시 곤지암읍 건업길 195"},
  {"name": "그린힐 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 광주시 곤지암읍 내선길 176"},
  {"name": "강남300 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 광주시 새말길 353(목동)"},
  {"name": "로제비앙GC", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 광주시 곤지암읍 오항길 180"},
  {"name": "곤지암GC", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 광주시 도척면 도척윗로 280"},
  {"name": "중부컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 광주시 곤지암읍 경충대로 451"},
  {"name": "뉴서울컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 광주시 삼지곡길 95(삼동)"},
  {"name": "캐슬렉스골프클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 하남시 감이로 317(감이동)"},
  {"name": "안양컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 군포시 군포로364(부곡동)"},
  {"name": "레이크우드 골프장(회원제)", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 양주시 만송로 244"},
  {"name": "레이크우드 골프장(비회원제)", "region": "경기", "holes": 9, "type": "비회원제", "address": "경기도 양주시 만송로 244"},
  {"name": "송추 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 양주시 광적면 쇠장이길 435"},
  {"name": "에이치원 클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 이천시 호법면 장자터로 115"},
  {"name": "뉴스프링빌골프장", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 이천시 모가면 사실로 527번길 158"},
  {"name": "뉴스프링빌골프장(대중형)", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 이천시 모가면 사실로 527번길 158"},
  {"name": "비에이비스타골프장(회원)", "region": "경기", "holes": 41, "type": "회원제", "address": "경기도 이천시 모가면 어농로 272"},
  {"name": "비에이비스타컨트리클럽(비회원)", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 이천시 모가면 어농로 272"},
  {"name": "더반 골프클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 이천시 대월면 대월로 627-141"},
  {"name": "사우스스프링스C.C", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 이천시 모가면 공원로 64"},
  {"name": "블랙스톤골프장(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 이천시 장호원읍 장여로 459-160"},
  {"name": "블랙스톤골프장(대중형)", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 이천시 장호원읍 장여로 459-160"},
  {"name": "이천실크밸리골프클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 이천시 율면 임오산로 296"},
  {"name": "마이다스레이크 이천 골프&리조트", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 이천시 설성면 설가로 602"},
  {"name": "웰링턴컨트리클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 이천시 모가면 사실로 725번길 119-73"},
  {"name": "더크로스비골프클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 이천시 호법면 중부대로798번길 177"},
  {"name": "파인크리크C.C", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 안성시 양성면 안성맞춤대로 2417-13"},
  {"name": "골프클럽Q", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 죽산면 장계길 20-229"},
  {"name": "골프존카운티 안성H", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 보개면 보삼로 302"},
  {"name": "마에스트로 CC", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 양성면 안성맞춤대로 2134-36"},
  {"name": "안성컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 안성시 죽산면 걸미로 487"},
  {"name": "안성베네스트G.C", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 안성시 금광면 삼흥로 660"},
  {"name": "안성베네스트골프클럽 일반대중홀", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 안성시 금광면 삼흥로 660"},
  {"name": "신안컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 안성시 고삼면 개울말길 149"},
  {"name": "신안 퍼블릭 CC", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 안성시 고삼면 개울말길 149"},
  {"name": "윈체스트 골프클럽 대중", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 서운면 오촌길 97-31"},
  {"name": "포웰CC 안성", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 양성면 약산길 67-6"},
  {"name": "골프존카운티 안성W", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 안성시 양성면 교동길 19-70"},
  {"name": "한림안성", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 안성시 양성면 양성로 349-61"},
  {"name": "에덴블루 컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 안성시 죽산면 녹배길 175"},
  {"name": "이글몬트CC", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 안성시 보개면 보삼로 106"},
  {"name": "필로스 골프클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 포천시 일동면 운악청계로 1507"},
  {"name": "포천아도니스 C.C", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 포천시 신북면 포천로 2499"},
  {"name": "포천아도니스 대중골프장", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 포천시 신북면 포천로 2499"},
  {"name": "베어크리크골프클럽", "region": "경기", "holes": 36, "type": "대중제", "address": "경기도 포천시 화현면 달인동로 35"},
  {"name": "몽베르 컨트리클럽(회원제)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 포천시 영북면 산정호수로 359-12"},
  {"name": "몽베르 컨트리클럽(비회원제)", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 포천시 영북면 산정호수로 359-13"},
  {"name": "일동레이크 골프클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 포천시 일동면 화동로 738"},
  {"name": "일동레이크대중제골프장", "region": "경기", "holes": 12, "type": "대중제", "address": "경기도 포천시 일동면 화동로 738"},
  {"name": "푸른솔 골프클럽 포천", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 포천시 가산면 금우로276"},
  {"name": "포천힐스 컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 포천시 군내면 반월산성로 375번길 34"},
  {"name": "포레스트힐 컨트리클럽", "region": "경기", "holes": 24, "type": "대중제", "address": "경기도 포천시 화현면 봉화로 253"},
  {"name": "참밸리 컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 포천시 삼육사로 1982"},
  {"name": "샴발라 컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 포천시 군내면 청군로 2856-93"},
  {"name": "라싸 골프클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 포천시 이동면 제비울2길 161"},
  {"name": "힐마루 골프앤리조트 포천", "region": "경기", "holes": 45, "type": "대중제", "address": "경기도 포천시 영중면 금화봉 4길 77-1"},
  {"name": "더스타휴 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 양평군 양동면 양동로 756"},
  {"name": "양평TPC GC", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 양평군 지평면 대평평장길 113-8"},
  {"name": "YJC골프클럽", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 여주시 월평로 78"},
  {"name": "남여주대중골프장", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 여주시 가여로 532"},
  {"name": "소피아그린", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 여주시 점동면 소피아그린길 84"},
  {"name": "솔모로골프장", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 여주시 가남읍 솔모로그린길 171"},
  {"name": "금강컨트리클럽(회원)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 가남읍 여주남로 541"},
  {"name": "금강컨트리클럽(대중)", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 여주시 가남읍 여주남로 541"},
  {"name": "자유컨트리클럽", "region": "경기", "holes": 36, "type": "회원제", "address": "경기도 여주시 가남읍 자유그린길 69"},
  {"name": "빅토리아일반대중골프장", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 여주시 가남읍 송삼로 191"},
  {"name": "아리지 골프장", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 여주시 가남읍 아리지그린길 68"},
  {"name": "이포골프장", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 금사면 장흥로 416"},
  {"name": "렉스필드 컨트리클럽(회원)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 산북면 광여로 1115"},
  {"name": "렉스필드 컨트리클럽(비회원)", "region": "경기", "holes": 9, "type": "비회원제", "address": "경기도 여주시 산북면 광여로 1115"},
  {"name": "블루헤런G.C", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 대신면 고달사로 67"},
  {"name": "신라컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 여주시 북내면 신라그린길 84"},
  {"name": "스카이밸리골프장(회원)", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 북내면 운촌길 254"},
  {"name": "스카이밸리골프장(비회원)", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 북내면 운촌길 254"},
  {"name": "캐슬파인골프클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 강천면 부평로 580"},
  {"name": "해슬리나인브릿지 컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 여주시 명품1로 76"},
  {"name": "세라지오GC", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 여양로 530"},
  {"name": "360도 컨트리클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 강천면 부평로 609"},
  {"name": "여주썬밸리 컨트리클럽", "region": "경기", "holes": 9, "type": "대중제", "address": "경기도 여주시 강천면 강문로 872"},
  {"name": "페럼클럽", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 점동면 점동로 181"},
  {"name": "ROUTE52CC", "region": "경기", "holes": 18, "type": "대중제", "address": "경기도 여주시 북내면 중암1길 36"},
  {"name": "티클라우드컨트리클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 동두천시 평화로 3202"},
  {"name": "썬힐G.C", "region": "경기", "holes": 36, "type": "대중제", "address": "경기도 가평군 조종면 운악청계로 809"},
  {"name": "마이다스밸리 청평 골프클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 가평군 설악면 다락재로 73-111"},
  {"name": "프리스틴밸리 골프클럽", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 가평군 설악면 유명로 1243-199"},
  {"name": "아난티클럽서울", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 가평군 설악면 유명로 961-34"},
  {"name": "가평 베네스트G.C", "region": "경기", "holes": 27, "type": "회원제", "address": "경기도 가평군 상면 둔덕말길 232"},
  {"name": "크리스탈밸리C.C", "region": "경기", "holes": 18, "type": "회원제", "address": "경기도 가평군 상면 대보간선로 602-111"},
  {"name": "리앤리C.C", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 가평군 조종면 운악청계로 702-24"},
  {"name": "베뉴지CC", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 가평군 가평읍 용추로 171번길 100"},
  {"name": "자유로컨트리클럽", "region": "경기", "holes": 27, "type": "대중제", "address": "경기도 연천군 백학면 노아로297번길 179-55"},
  {"name": "창원컨트리클럽", "region": "경남", "holes": 18, "type": "회원제", "address": "창원시 의창구 대봉로 137"},
  {"name": "용원컨트리클럽", "region": "경남", "holes": 27, "type": "회원제", "address": "창원시 진해구 가주로 133"},
  {"name": "아라미르골프앤리조트", "region": "경남", "holes": 36, "type": "비회원제", "address": "창원시 진해구 수제로 36"},
  {"name": "진주컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "진주시 진성면 진성로 464번길 82"},
  {"name": "통영동원로얄컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "통영시 산양읍 담안길 240"},
  {"name": "서경타니CC", "region": "경남", "holes": 27, "type": "대중제", "address": "사천시 곤양면 흥신로 210"},
  {"name": "서경타니CC", "region": "경남", "holes": 9, "type": "대중제", "address": "사천시 곤양면 흥신로 210"},
  {"name": "삼삼컨트리클럽", "region": "경남", "holes": 9, "type": "대중제", "address": "사천시 축동면 화당산로 224"},
  {"name": "골프존카운티 사천", "region": "경남", "holes": 27, "type": "대중제", "address": "사천시 서포면 구송로 151"},
  {"name": "가야컨트리클럽", "region": "경남", "holes": 45, "type": "회원제", "address": "김해시 인제로 495"},
  {"name": "가야컨트리클럽", "region": "경남", "holes": 9, "type": "대중제", "address": "김해시 인제로 495"},
  {"name": "김해정산컨트리클럽", "region": "경남", "holes": 27, "type": "회원제", "address": "김해시 주촌면 서부로 1637번길 299-194"},
  {"name": "포웰CC 김해", "region": "경남", "holes": 18, "type": "회원제", "address": "김해시 진례면 고모로 134번길 54-49"},
  {"name": "김해상록컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "김해시 한림면 김해대로 974번길 198"},
  {"name": "리더스컨트리클럽", "region": "경남", "holes": 27, "type": "대중제", "address": "밀양시 활성로 455"},
  {"name": "밀양컨트리클럽", "region": "경남", "holes": 9, "type": "대중제", "address": "밀양시 부북면 전사포리 832"},
  {"name": "밀양노벨컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "밀양시 단장면 단장로 946"},
  {"name": "밀양에스파크골프리조트", "region": "경남", "holes": 18, "type": "대중제", "address": "밀양시 단장면 미촌리 889"},
  {"name": "거제드비치골프클럽", "region": "경남", "holes": 18, "type": "회원제", "address": "거제시 장목면 거제북로 1573"},
  {"name": "거제뷰컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "거제시 거제면 두동로 259-80"},
  {"name": "통도파인이스트컨트리클럽", "region": "경남", "holes": 36, "type": "회원제", "address": "양산시 하북면 신평남부길 78-130"},
  {"name": "동부산컨트리클럽", "region": "경남", "holes": 27, "type": "회원제", "address": "양산시 매곡외산로 282"},
  {"name": "에이원컨트리클럽", "region": "경남", "holes": 27, "type": "회원제", "address": "양산시 덕명로 190"},
  {"name": "에덴밸리컨트리클럽", "region": "경남", "holes": 18, "type": "회원제", "address": "양산시 원동면 어실로 910"},
  {"name": "양산컨트리클럽", "region": "경남", "holes": 27, "type": "대중제", "address": "양산시 상북면 충렬로 687"},
  {"name": "다이아몬드컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "양산시 상북면 공원로 305-391"},
  {"name": "양산동원로얄CC", "region": "경남", "holes": 18, "type": "대중제", "address": "양산시 어실로 380-45"},
  {"name": "의령친환경골프장", "region": "경남", "holes": 9, "type": "대중제", "address": "의령군 의령읍 남강로 417"},
  {"name": "의령 리온컨트리클럽", "region": "경남", "holes": 27, "type": "대중제", "address": "의령군 칠곡면 지굴산로 101-33"},
  {"name": "골프존카운티 경남", "region": "경남", "holes": 18, "type": "대중제", "address": "함안군 칠원면 운무로 470"},
  {"name": "부곡컨트리클럽", "region": "경남", "holes": 18, "type": "회원제", "address": "창녕군 부곡면 온천로 445"},
  {"name": "힐마루컨트리클럽", "region": "경남", "holes": 18, "type": "회원제", "address": "창녕군 장마면 영산계성로 469-195"},
  {"name": "힐마루컨트리클럽", "region": "경남", "holes": 18, "type": "대중제", "address": "창녕군 장마면 영산계성로 469-195"},
  {"name": "고성노벨컨트리클럽", "region": "경남", "holes": 27, "type": "회원제", "address": "고성군 회화면 회진로 567"},
  {"name": "고성컨트리클럽", "region": "경남", "holes": 9, "type": "대중제", "address": "고성군 고성읍 월평3길 250"},
  {"name": "아난티남해CC", "region": "경남", "holes": 9, "type": "대중제", "address": "남해군 남면 남서대로 1179번길 40-109"},
  {"name": "아난티남해GC", "region": "경남", "holes": 9, "type": "대중제", "address": "남해군 남면 남서대로 1179번길 40-109"},
  {"name": "사우스케이프오너스클럽", "region": "경남", "holes": 18, "type": "비회원제", "address": "남해군 창선면 흥선로 1545"},
  {"name": "경남스카이뷰CC", "region": "경남", "holes": 18, "type": "대중제", "address": "함양군 서상면 소로길 226"},
  {"name": "거창친환경대중골프장", "region": "경남", "holes": 9, "type": "대중제", "address": "거창군 가조면 우륵길 410-284"},
  {"name": "클럽디거창", "region": "경남", "holes": 27, "type": "대중제", "address": "거창군 신원면 덕산리 산 13번지"},
  {"name": "아델스코트 컨트리클럽", "region": "경남", "holes": 27, "type": "대중제", "address": "합천군 가야면 가조가야로 1916-35"},
  {"name": "오션힐스포항C.C", "region": "경북", "holes": 18, "type": "회원제", "address": "경상북도 포항시 북구 송라면 대전길 7"},
  {"name": "오션힐스포항C.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 포항시 북구 송라면 대전길 7"},
  {"name": "청하이스턴C.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 포항시 청하면 용산길 94"},
  {"name": "포항C.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 포항시 송라면 동해대로 2751번길 123"},
  {"name": "경주신라C.C", "region": "경북", "holes": 36, "type": "회원제", "address": "경상북도 경주시 보문로 319"},
  {"name": "보문G.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 경주시 보문로 182-14"},
  {"name": "경주C.C", "region": "경북", "holes": 27, "type": "대중제", "address": "경상북도 경주시 보문로 182-98"},
  {"name": "마우나오션C.C", "region": "경북", "holes": 18, "type": "회원제", "address": "경상북도 경주시 양남면 동남로 982"},
  {"name": "마우나오션블루", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 양남면 동남로 982"},
  {"name": "가든골프클럽", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 불국로 289-17"},
  {"name": "우리G.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 양남면 동남로 972"},
  {"name": "서라벌G.C", "region": "경북", "holes": 36, "type": "대중제", "address": "경상북도 경주시 외동읍 내외로 577-189"},
  {"name": "서라벌G.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 외동읍 내외로 577-189"},
  {"name": "골프존카운티 감포", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 경주시 감포읍 동해안로 1819-59"},
  {"name": "디아너스C.C", "region": "경북", "holes": 27, "type": "회원제", "address": "경상북도 경주시 보불로 391"},
  {"name": "선리치G.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 안강읍 검단장골길 181-17"},
  {"name": "안강레전드G.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 경주시 안강읍 낙산길 85"},
  {"name": "이스트힐C.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 경주시 양남면 외남로 1377"},
  {"name": "힐스카이C.C", "region": "경북", "holes": 24, "type": "대중제", "address": "경상북도 경주시 천북면 천강로 412-299"},
  {"name": "애플밸리C.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 김천시 어모면 작점로 606"},
  {"name": "포도C.C", "region": "경북", "holes": 27, "type": "대중제", "address": "경상북도 김천시 구성면 남김천대로 2532"},
  {"name": "남안동C.C", "region": "경북", "holes": 18, "type": "회원제", "address": "경상북도 안동시 일직면 풍일로 1887"},
  {"name": "안동리버힐C.C", "region": "경북", "holes": 18, "type": "회원제", "address": "경상북도 안동시 풍천면 풍일로 1572"},
  {"name": "안동레이크골프클럽", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 안동시 관광단지로 316"},
  {"name": "골프존카운티 선산", "region": "경북", "holes": 18, "type": "회원제", "address": "경상북도 구미시 산동면 강동로 953-73"},
  {"name": "골프존카운티 구미", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 구미시 산동면 강동로 953-74"},
  {"name": "구미C.C", "region": "경북", "holes": 27, "type": "대중제", "address": "경상북도 구미시 장천면 송백로 229"},
  {"name": "오펠G.C", "region": "경북", "holes": 27, "type": "회원제", "address": "경상북도 영천시 고경면 호국로 1221-24"},
  {"name": "영천C.C", "region": "경북", "holes": 27, "type": "회원제", "address": "경상북도 영천시 임고면 방목길 34-2"},
  {"name": "시엘G.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 영천시 청통면 청통로 334-41"},
  {"name": "청통골프장", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 영천시 청통면 청통로 733"},
  {"name": "블루원상주골프리조트", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 상주시 모서면 화현3길 127"},
  {"name": "뉴스프링빌Ⅱ", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 상주시 모서면 백화로 40"},
  {"name": "문경레저타운골프장", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 문경시 마성면 문경골프장길 240"},
  {"name": "대구C.C", "region": "경북", "holes": 27, "type": "회원제", "address": "경상북도 경산시 진량읍 일연로 718-42"},
  {"name": "인터불고컨트리클럽", "region": "경북", "holes": 27, "type": "회원제", "address": "경상북도 경산시 삼성현로 614-26"},
  {"name": "엠스클럽의성", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 의성군 봉양면 농공마전길 125-78"},
  {"name": "엠스클럽의성", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 의성군 봉양면 농공마전길 125-78"},
  {"name": "파라지오C.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 의성군 봉양면 농공마전길 167"},
  {"name": "오션비치C.C", "region": "경북", "holes": 27, "type": "대중제", "address": "경상북도 영덕군 강구면 동해대로 4265-43"},
  {"name": "그레이스C.C", "region": "경북", "holes": 27, "type": "대중제", "address": "경상북도 청도군 이서면 서녁길 91"},
  {"name": "오션힐스청도G.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 청도군 매전면 곰티로 370-204"},
  {"name": "펜타뷰골프클럽", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 청도군 금천면 금천로 709"},
  {"name": "유니밸리C.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 고령군 고령읍 일량로 588"},
  {"name": "마스터피스CC", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 고령군 쌍림면 산막길 47-80"},
  {"name": "대가야CC", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 고령군 대가야읍 대가야로 1103"},
  {"name": "다산 샤인힐CC", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 고령군 다산면 벌지로 175-115"},
  {"name": "파미힐스C.C", "region": "경북", "holes": 36, "type": "회원제", "address": "경상북도 칠곡군 왜관읍 봉계로 263"},
  {"name": "마이다스 구미 골프아카데미", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 칠곡군 가산면 학하2길 54-171"},
  {"name": "세븐밸리C.C", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 칠곡군 왜관읍 봉계3길 180"},
  {"name": "칠곡아이위시C.C", "region": "경북", "holes": 9, "type": "대중제", "address": "경상북도 칠곡군 기산면 노석1길 49-112"},
  {"name": "한맥C.C&노블리아", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 예천군 호명면 한맥골프장길 72"},
  {"name": "마린CC", "region": "경북", "holes": 18, "type": "대중제", "address": "경상북도 울진군 매화면 매화로 115-99"},
  {"name": "빛고을컨트리클럽", "region": "광주", "holes": 9, "type": "대중제", "address": "광주광역시 남구 효우로 153(노대동)"},
  {"name": "에콜리안광산골프장", "region": "광주", "holes": 9, "type": "대중제", "address": "광주광역시 광산구 오목내길 26(연산동)"},
  {"name": "어등산컨트리클럽", "region": "광주", "holes": 27, "type": "대중제", "address": "광주광역시 광산구 무진대로 31(운수동)"},
  {"name": "팔공컨트리클럽", "region": "대구", "holes": 18, "type": "회원제", "address": "대구광역시 동구 팔공산로 237길 186"},
  {"name": "냉천컨트리클럽", "region": "대구", "holes": 9, "type": "대중제", "address": "대구광역시 달성군 가창면 가창로 1037-9"},
  {"name": "구니컨트리클럽", "region": "대구", "holes": 18, "type": "대중제", "address": "대구광역시 군위군 군위읍 도군로 2450"},
  {"name": "오펠골프클럽", "region": "대구", "holes": 18, "type": "대중제", "address": "대구광역시 군위군 산성면 부흥로 227"},
  {"name": "이지스카이컨트리클럽", "region": "대구", "holes": 18, "type": "대중제", "address": "대구광역시 군위군 군위읍 대흥1길 48-100"},
  {"name": "유성컨트리클럽", "region": "대전", "holes": 18, "type": "회원제", "address": "대전 유성구 현충원로 200(덕명동 215-7번지)"},
  {"name": "대덕복지센터", "region": "대전", "holes": 9, "type": "대중제", "address": "대전 유성구 유성대로 1689번길 69(전민동 463번지)"},
  {"name": "금실대덕밸리CC", "region": "대전", "holes": 9, "type": "대중제", "address": "대전 유성구 테크노중앙로 210(용산동 676번지)"},
  {"name": "부산컨트리클럽", "region": "부산", "holes": 18, "type": "회원제", "address": "부산광역시 금정구 중앙대로2327번길 11"},
  {"name": "동래베네스트골프클럽", "region": "부산", "holes": 18, "type": "회원제", "address": "부산광역시 금정구 하정로 66"},
  {"name": "하이스트컨트리클럽", "region": "부산", "holes": 9, "type": "대중제", "address": "부산광역시 강서구 과학산단1로 172"},
  {"name": "해라컨트리클럽", "region": "부산", "holes": 9, "type": "대중제", "address": "부산광역시 강서구 과학산단로 306번길 77"},
  {"name": "아시아드컨트리클럽", "region": "부산", "holes": 27, "type": "회원제", "address": "부산광역시 기장군 일광읍 차양길 26"},
  {"name": "해운대컨트리클럽", "region": "부산", "holes": 27, "type": "회원제", "address": "부산광역시 기장군 정관면 병산2로 265"},
  {"name": "베이사이드골프클럽", "region": "부산", "holes": 27, "type": "회원제", "address": "부산광역시 기장군 일광읍 이천8길 100"},
  {"name": "해운대비치골프앤리조트", "region": "부산", "holes": 18, "type": "회원제", "address": "부산광역시 기장군 기장읍 대변로 74"},
  {"name": "기장동원로얄컨트리클럽", "region": "부산", "holes": 9, "type": "대중제", "address": "부산광역시 기장군 기장읍 반송로 1345-52"},
  {"name": "스톤게이트컨트리클럽", "region": "부산", "holes": 18, "type": "대중제", "address": "부산광역시 기장군 일광읍 곡천길 317"},
  {"name": "인서울27골프클럽", "region": "서울", "holes": 27, "type": "비회원제", "address": "서울특별시 강서구 오정로 443-198"},
  {"name": "세종에머슨컨트리클럽", "region": "세종", "holes": 27, "type": "회원제", "address": "세종특별자치시 전의면 운주산로 1510"},
  {"name": "건설공제조합세종필드골프클럽", "region": "세종", "holes": 18, "type": "대중제", "address": "세종특별자치시 정안세종로  1569"},
  {"name": "세종레이캐슬골프&리조트", "region": "세종", "holes": 27, "type": "대중제", "address": "세종특별자치시 전의면 의당전의로 252"},
  {"name": "보라골프장", "region": "울산", "holes": 27, "type": "회원제", "address": "울주군 삼동면 삼동로 404"},
  {"name": "삼남골프장", "region": "울산", "holes": 9, "type": "대중제", "address": "울주군 삼남면 방기가천로 179"},
  {"name": "더골프골프장", "region": "울산", "holes": 18, "type": "대중제", "address": "울주군 서생면 용연길 206-52"},
  {"name": "울산골프장", "region": "울산", "holes": 27, "type": "회원제", "address": "울주군 웅촌면 웅촌로 1"},
  {"name": "베이스타즈CC", "region": "울산", "holes": 18, "type": "대중제", "address": "북구 미포산업로 800"},
  {"name": "오르비스골프클럽", "region": "울산", "holes": 18, "type": "대중제", "address": "울주군 온양읍 망양리 산14-9"},
  {"name": "인천국제컨트리클럽", "region": "인천", "holes": 18, "type": "회원제", "address": "인천시 서구 도요지로 37"},
  {"name": "잭 니클라우스 골프클럽 코리아", "region": "인천", "holes": 18, "type": "회원제", "address": "인천시 연수구 아카데미로 209"},
  {"name": "송도골프클럽", "region": "인천", "holes": 8, "type": "대중제", "address": "인천시 연수구 능허대로 236"},
  {"name": "인천그랜드컨트리클럽", "region": "인천", "holes": 18, "type": "대중제", "address": "인천시 서구 원석로 195"},
  {"name": "클럽72(바다)", "region": "인천", "holes": 63, "type": "대중제", "address": "인천시 중구 공항동로 392"},
  {"name": "클럽72(하늘)", "region": "인천", "holes": 18, "type": "대중제", "address": "인천시 중구 공항동로135번길 267"},
  {"name": "베어즈베스트청라골프클럽", "region": "인천", "holes": 27, "type": "대중제", "address": "인천시 서구 청라대로 316번길 45"},
  {"name": "드림파크골프장", "region": "인천", "holes": 36, "type": "대중제", "address": "인천시 서구 거월로 61"},
  {"name": "골프존카운티 송도 골프장", "region": "인천", "holes": 18, "type": "대중제", "address": "인천시 연수구 인천신항대로 1120"},
  {"name": "석모도컨트리클럽", "region": "인천", "holes": 18, "type": "대중제", "address": "인천시 강화군 어류정길 177"},
  {"name": "오렌지듄스 영종골프클럽", "region": "인천", "holes": 18, "type": "대중제", "address": "인천시 중구 운서동 2850-43번지 일원"},
  {"name": "강화 선두리 골프장", "region": "인천", "holes": 9, "type": "대중제", "address": "인천시 강화군 해안남로 474번길 59"},
  {"name": "베르힐CC 영종", "region": "인천", "holes": 36, "type": "대중제", "address": "인천시 중구 한상중앙로 66(중산동)"},
  {"name": "여수시티파크골프&호텔", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 여수시 좌수영로 641"},
  {"name": "디오션CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 여수시 화양면 안포리 1917"},
  {"name": "세이지우드 여수경도", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 여수시 대경도길 111"},
  {"name": "포라이즌", "region": "전남", "holes": 27, "type": "회원제", "address": "전남 순천시 별량면 오실길 333"},
  {"name": "파인힐스CC", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 순천시 주암면 송강사길 99"},
  {"name": "순천CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 순천시 별량면 동화사길 85"},
  {"name": "골프존카운티", "region": "전남", "holes": 36, "type": "대중제", "address": "전남 순천시 주암면 행정1길 77"},
  {"name": "순천부영CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 순천시 해룡면 신대로 188"},
  {"name": "골드레이크CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 나주시 남평읍 나주호로 442-129"},
  {"name": "골드레이크CC", "region": "전남", "holes": 18, "type": "회원제", "address": "전남 나주시 남평읍 나주호로 442-129"},
  {"name": "해피니스CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 나주시 다도면 다도로 171-60"},
  {"name": "해피니스CC", "region": "전남", "holes": 18, "type": "회원제", "address": "전남 나주시 다도면 다도로 171-60"},
  {"name": "나주CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 나주시 공산면 상방신포길 154-32"},
  {"name": "나주힐스CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 나주시 공산면 삼방신포길 160-27"},
  {"name": "광양CC", "region": "전남", "holes": 6, "type": "대중제", "address": "전남 광양시 가야로 223"},
  {"name": "창평CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 담양군 창평면 오강리 27-2"},
  {"name": "레이나CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 담양군 담양읍 깊은실길 169"},
  {"name": "죽향CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 담양군 창평면 창평로 159"},
  {"name": "광주CC", "region": "전남", "holes": 27, "type": "회원제", "address": "전남 곡성군 옥과면 입면로 455"},
  {"name": "옥과기안CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 곡성군 옥과면 소룡리 427-2"},
  {"name": "르오네뜨CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 곡성군 오산면 오산로 819-126"},
  {"name": "보성CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 보성군 조성면 대곡리 1117"},
  {"name": "보성에덴CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 보성군 보성읍 쾌상리 1385"},
  {"name": "엘리체CC", "region": "전남", "holes": 18, "type": "회원제", "address": "전남 화순군 춘양면 장곡길 55"},
  {"name": "화순CC", "region": "전남", "holes": 27, "type": "회원제", "address": "전남 화순군 도곡면 천태로 1000-151"},
  {"name": "조아밸리CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 화순군 도곡면 고인돌2로 450"},
  {"name": "무등산CC", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 화순군 화순읍 오성로 292-90"},
  {"name": "JNJ골프리조트", "region": "전남", "holes": 27, "type": "대중제", "address": "장흥군 장평면 제산기동로 326"},
  {"name": "다산베아채골프&리조트", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 강진군 도암면 학장용산길 101"},
  {"name": "오시아노골프클럽", "region": "전남", "holes": 9, "type": "대중제", "address": "해남군 화원면 시아로 224"},
  {"name": "파인비치골프링크스", "region": "전남", "holes": 18, "type": "대중제", "address": "해남군 화원면 시아로 224"},
  {"name": "솔라시도CC", "region": "전남", "holes": 18, "type": "대중제", "address": "해남군 산이면 산이로 2247"},
  {"name": "아크로CC", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 영암군 금정면 안적동길 403"},
  {"name": "cosmos 1", "region": "전남", "holes": 18, "type": "대중제", "address": "영암군 삼호읍 에프원로 121-4"},
  {"name": "골프존카운티 영암", "region": "전남", "holes": 45, "type": "대중제", "address": "영암군 삼호읍 에프원로 121-1"},
  {"name": "무안CC", "region": "전남", "holes": 54, "type": "대중제", "address": "전남 무안군 청계면 도대리 818"},
  {"name": "클린밸리CC", "region": "전남", "holes": 18, "type": "대중제", "address": "전남 무안군 청계면 태봉길 33-100"},
  {"name": "엘리체CC", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 함평군 학교면 서당매길 242"},
  {"name": "천지CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 함평군 함장로 889-11"},
  {"name": "베르힐컨트리클럽", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 함평군 대동면 대동길 408"},
  {"name": "웨스트오션CC", "region": "전남", "holes": 18, "type": "대중제", "address": "영광군 백수읍 해안로 1362-70"},
  {"name": "에콜리안영광골프장", "region": "전남", "holes": 9, "type": "대중제", "address": "영광군 영광읍 월현로 1길 40"},
  {"name": "푸른솔 골프클럽", "region": "전남", "holes": 27, "type": "대중제", "address": "전남 장성군 동화면 임정로 155"},
  {"name": "백양우리CC", "region": "전남", "holes": 9, "type": "대중제", "address": "전남 장성군 북이면 사거리 752-1"},
  {"name": "전주월드컵골프장", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 전주시 덕진구 온고을로 672"},
  {"name": "군산CC", "region": "전북", "holes": 81, "type": "대중제", "address": "전북특별자치도 군산시 옥서면 남산군로 1685"},
  {"name": "익산컨트리클럽", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 익산시 무왕로38길 111"},
  {"name": "상떼힐CC", "region": "전북", "holes": 6, "type": "대중제", "address": "전북특별자치도 익산시 무왕로38길 111"},
  {"name": "웅포컨트리클럽", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 익산시 웅포면 강변로 130"},
  {"name": "포세븐금강컨트리클럽", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 익산시 웅포면 강변로 130"},
  {"name": "태인CC", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 정읍시 태인면 상증길 28"},
  {"name": "태인CC", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 정읍시 태인면 상증길 28"},
  {"name": "내장산골프&리조트", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 정읍시 첨단과학로 476"},
  {"name": "남원상록골프장", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 남원시 대산면 월계길 11"},
  {"name": "골프존 카운티 드래곤", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 남원시 대산면 대사로 498"},
  {"name": "골프존 카운티 드래곤", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 남원시 대산면 대사로 498"},
  {"name": "아네스빌CC", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 김제시 황산면 높은메길 160-39"},
  {"name": "에스페란사GC", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 김제시 금구면 낙산로 120"},
  {"name": "김제스파힐스CC", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 김제시 온천길 37"},
  {"name": "더나인골프클럽", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 김제시 금구면 대화1길 8-75"},
  {"name": "OKCC", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 완주군 소양면 화심리 300"},
  {"name": "케이밸리컨트리클럽", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 완주군 운주면 산북리 65-4"},
  {"name": "써미트CC", "region": "전북", "holes": 27, "type": "대중제", "address": "전북특별자치도 진안군 부귀면 부귀로 72-161"},
  {"name": "무주덕유산CC", "region": "전북", "holes": 18, "type": "회원제", "address": "전북특별자치도 무주군 설천면 만선로 185"},
  {"name": "골프존카운티무주", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 무주군 안성면 장무로 1537-21"},
  {"name": "장수골프리조트", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 장수군 계남면 장안산로 303"},
  {"name": "전주샹그릴라CC", "region": "전북", "holes": 27, "type": "회원제", "address": "전북특별자치도 임실군 신덕면 수지로 559-90"},
  {"name": "금과골프장", "region": "전북", "holes": 6, "type": "대중제", "address": "전북특별자치도 순창군 금과면 담순로 716"},
  {"name": "디케이레저", "region": "전북", "holes": 9, "type": "대중제", "address": "전북특별자치도 순창군 순창읍 금산로 152"},
  {"name": "고창CC", "region": "전북", "holes": 21, "type": "대중제", "address": "전북특별자치도 고창군 심원면 애향갯벌로 70"},
  {"name": "골프존카운티선운", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 고창군 아산면 운곡로 418"},
  {"name": "석정힐CC", "region": "전북", "holes": 18, "type": "대중제", "address": "전북특별자치도 고창군 고창읍 석정2로 192"},
  {"name": "타미우스cc", "region": "제주", "holes": 27, "type": "회원제", "address": "제주특별자치도 제주시 애월읍 화전길 201"},
  {"name": "그린필드GC", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 조천읍 번영로 1040-70"},
  {"name": "라헨느CC", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 봉개동 241-13"},
  {"name": "볼카노골프앤리조트", "region": "제주", "holes": 27, "type": "회원제", "address": "제주특별자치도 서귀포시 산록남로 1391"},
  {"name": "테디밸리", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 한창로 365"},
  {"name": "㈜그랜드부민 꿈드림목장", "region": "제주", "holes": 9, "type": "대중제", "address": "제주특별자치도 제주시 516로 2596-117"},
  {"name": "에코랜드", "region": "제주", "holes": 27, "type": "대중제", "address": "제주특별자치도 제주시 조천읍 번영로 1278-169"},
  {"name": "라온골프클럽", "region": "제주", "holes": 27, "type": "대중제", "address": "제주특별자치도 제주시 한경면 용금로 998"},
  {"name": "크라운CC", "region": "제주", "holes": 27, "type": "대중제", "address": "제주특별자치도 제주시 조천읍 북선로 125"},
  {"name": "더시에나CC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 제주시 516로 2695"},
  {"name": "아덴힐", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 제주시 화전길 82"},
  {"name": "한라산CC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 제주시 선돌목동길 56-46"},
  {"name": "플라자CC", "region": "제주", "holes": 9, "type": "대중제", "address": "제주특별자치도 제주시 명림로 575-107"},
  {"name": "부영CC", "region": "제주", "holes": 27, "type": "대중제", "address": "제주특별자치도 서귀포시 남원읍 남조로 960"},
  {"name": "서귀포팬텀 골프앤리조트", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 산록남로 2914"},
  {"name": "중문GC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 중문관광로 72번길 60"},
  {"name": "스프링데일", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 남원읍 서성로 459"},
  {"name": "더클래식CC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 남원읍 남조로 1105"},
  {"name": "샤인빌파크CC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 표선면 가시로 384"},
  {"name": "골프존카운티오라", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 오라남로 130-16"},
  {"name": "골프존카운티오라", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 제주시 오라남로 130-16"},
  {"name": "엘리시안제주", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 평화로 1738-116"},
  {"name": "엘리시안제주", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 제주시 평화로 1738-116"},
  {"name": "에버리스CC", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 평화로 1693-75"},
  {"name": "에버리스CC", "region": "제주", "holes": 9, "type": "대중제", "address": "제주특별자치도 제주시 평화로 1693-75"},
  {"name": "아난티클럽제주", "region": "제주", "holes": 9, "type": "회원제", "address": "제주특별자치도 제주시 선유로 445-55"},
  {"name": "아난티클럽제주", "region": "제주", "holes": 27, "type": "대중제", "address": "제주특별자치도 제주시 선유로 445-55"},
  {"name": "블랙스톤제주", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 제주시 한창로 925-122"},
  {"name": "블랙스톤제주", "region": "제주", "holes": 9, "type": "회원제", "address": "제주특별자치도 제주시 한창로 925-122"},
  {"name": "캐슬렉스제주", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 안덕면 평화로 1241"},
  {"name": "캐슬렉스제주", "region": "제주", "holes": 9, "type": "대중제", "address": "제주특별자치도 서귀포시 안덕면 평화로 1241"},
  {"name": "해비치CC", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 남원읍 원님로 399번길 319"},
  {"name": "해비치CC", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 남원읍 원님로 399번길 319"},
  {"name": "롯데스카이힐제주", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 상예로 530"},
  {"name": "롯데스카이힐제주", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 상예로 530"},
  {"name": "사이프러스골프", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 번영로 2300"},
  {"name": "사이프러스골프", "region": "제주", "holes": 18, "type": "대중제", "address": "제주특별자치도 서귀포시 번영로 2300"},
  {"name": "나인브릿지", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 안덕면 광평로 34-156"},
  {"name": "나인브릿지", "region": "제주", "holes": 6, "type": "대중제", "address": "제주특별자치도 서귀포시 안덕면 광평로 34-156"},
  {"name": "SK핀크스", "region": "제주", "holes": 18, "type": "회원제", "address": "제주특별자치도 서귀포시 안덕면 산록남로 863"},
  {"name": "SK핀크스", "region": "제주", "holes": 9, "type": "대중제", "address": "제주특별자치도 서귀포시 안덕면 산록남로 863"},
  {"name": "우정힐스 컨트리클럽", "region": "충남", "holes": 18, "type": "회원제", "address": "목천읍 충절로 1048-68"},
  {"name": "천안상록 골프장", "region": "충남", "holes": 27, "type": "대중제", "address": "수신면 수신로 576"},
  {"name": "골프존카운티 천안", "region": "충남", "holes": 18, "type": "대중제", "address": "병천면 매성2길 103"},
  {"name": "마론컨트리클럽", "region": "충남", "holes": 18, "type": "대중제", "address": "동남구 북면 납안5길 74"},
  {"name": "프린세스 골프클럽", "region": "충남", "holes": 18, "type": "대중제", "address": "공주시 정안면 방자들길 81-50(인풍리)"},
  {"name": "골드리버CC", "region": "충남", "holes": 9, "type": "대중제", "address": "공주시 의당면 신정말길 67-133(청룡리)"},
  {"name": "계룡산골프장", "region": "충남", "holes": 9, "type": "대중제", "address": "공주시 계룡면 아랫난댕이길 17(내흥리)"},
  {"name": "보령베이스CC", "region": "충남", "holes": 9, "type": "대중제", "address": "보령시 옥마벚길 10"},
  {"name": "에스앤 골프리조트", "region": "충남", "holes": 9, "type": "대중제", "address": "보령시 남포면 양항리 650-2"},
  {"name": "도고컨트리 구락부", "region": "충남", "holes": 18, "type": "회원제", "address": "선장면 삼봉산길 188"},
  {"name": "에스지아름다운골프&리조트", "region": "충남", "holes": 27, "type": "대중제", "address": "영인면 영인산로 440"},
  {"name": "서산수 골프앤리조트", "region": "충남", "holes": 18, "type": "대중제", "address": "서산시 대산읍 삼길포7로 8"},
  {"name": "더힐 컨트리클럽", "region": "충남", "holes": 9, "type": "대중제", "address": "논산시 상월면 선비로 1079"},
  {"name": "아리스타 CC", "region": "충남", "holes": 18, "type": "대중제", "address": "연무읍 황화정리 산100"},
  {"name": "파인스톤 컨트리클럽", "region": "충남", "holes": 18, "type": "대중제", "address": "당진시 송산면 무수들길 90"},
  {"name": "파나시아 골프클럽", "region": "충남", "holes": 9, "type": "대중제", "address": "당진시 신평면 계명길 33"},
  {"name": "플라밍고C.C", "region": "충남", "holes": 30, "type": "대중제", "address": "당진시 석문면 산단8로 299"},
  {"name": "에딘버러 컨트리클럽", "region": "충남", "holes": 18, "type": "회원제", "address": "금산군 진산면 살구정길 167"},
  {"name": "백제컨트리클럽", "region": "충남", "holes": 27, "type": "대중제", "address": "부여군 은산면 충절로 3734-82"},
  {"name": "㈜호텔롯데 스카이힐 부여CC", "region": "충남", "holes": 18, "type": "대중제", "address": "부여군 규암면 백제문로 470"},
  {"name": "골든베이골프&리조트", "region": "충남", "holes": 27, "type": "대중제", "address": "태안군 근흥면 정선포로 217"},
  {"name": "스톤비치컨트리클럽", "region": "충남", "holes": 18, "type": "대중제", "address": "태안군 근흥면 갈음이길 88"},
  {"name": "로얄링스1", "region": "충남", "holes": 18, "type": "대중제", "address": "태안군 태안읍 반곡길 284"},
  {"name": "로얄링스2", "region": "충남", "holes": 18, "type": "대중제", "address": "태안군 태안읍 반곡길 284"},
  {"name": "솔라고CC1", "region": "충남", "holes": 18, "type": "대중제", "address": "태안군 태안읍 소곳이길 92-234"},
  {"name": "솔라고CC2", "region": "충남", "holes": 18, "type": "대중제", "address": "태안군 태안읍 소곳이길 92-234"},
  {"name": "내포골프클럽", "region": "충남", "holes": 9, "type": "대중제", "address": "예산군 삽교읍 산수길 242(목리 1420)"},
  {"name": "그랜드cc", "region": "충북", "holes": 27, "type": "회원제", "address": "청주시 청원군 오창읍 꽃화산길 14"},
  {"name": "아난티 중앙골프클럽", "region": "충북", "holes": 27, "type": "회원제", "address": "진천군 백곡면 배티로 818-105"},
  {"name": "천 룡cc", "region": "충북", "holes": 27, "type": "회원제", "address": "진천군 이월면 진안로 347-123"},
  {"name": "세레니티cc", "region": "충북", "holes": 18, "type": "회원제", "address": "청주시 서원구 남이면 문곡구절골길 235"},
  {"name": "스 타cc", "region": "충북", "holes": 18, "type": "회원제", "address": "충주시 앙성면 상대촌1길 198"},
  {"name": "임페리얼레이크", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 금가면 다래울길 52"},
  {"name": "천 룡cc", "region": "충북", "holes": 9, "type": "대중제", "address": "진천군 이월면 진안로 425"},
  {"name": "시그너스cc", "region": "충북", "holes": 9, "type": "대중제", "address": "충주시 앙성면 중방곡길 57-44"},
  {"name": "시그너스cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 앙성면 중방곡길 57-44"},
  {"name": "떼제베운영", "region": "충북", "holes": 36, "type": "대중제", "address": "청주시 흥덕구 옥산면 동림2길 149"},
  {"name": "썬밸리cc", "region": "충북", "holes": 18, "type": "대중제", "address": "음성군 삼성면 법말길 49"},
  {"name": "중 원cc", "region": "충북", "holes": 27, "type": "대중제", "address": "충주시 산척면 인등로 392"},
  {"name": "레인보우힐스", "region": "충북", "holes": 27, "type": "대중제", "address": "음성군 생극면 차생로 168"},
  {"name": "히든밸리cc", "region": "충북", "holes": 27, "type": "대중제", "address": "진천군 백곡면 소토골길 61"},
  {"name": "골드나인cc", "region": "충북", "holes": 9, "type": "대중제", "address": "청주시 청원구 낭성면 산성로 1520-17"},
  {"name": "센테리움cc", "region": "충북", "holes": 27, "type": "대중제", "address": "충주시 노은면 솔고개로 750"},
  {"name": "대호단양cc", "region": "충북", "holes": 18, "type": "대중제", "address": "단양군 매포읍 고양5길 43"},
  {"name": "대영베이스cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 대소원면 성종두담길 113"},
  {"name": "골프존카운티 진천cc", "region": "충북", "holes": 27, "type": "대중제", "address": "진천군 진천읍 송강로 783-51"},
  {"name": "오창 에딘버러", "region": "충북", "holes": 9, "type": "대중제", "address": "청주시 청원구 오창읍 두릉유리로 846"},
  {"name": "이븐데일cc", "region": "충북", "holes": 18, "type": "대중제", "address": "청주시 상당구 미원면 대신2길 31"},
  {"name": "킹즈락cc", "region": "충북", "holes": 27, "type": "대중제", "address": "제천시 천남동 내토로7길 136"},
  {"name": "골프존카운티 화랑cc", "region": "충북", "holes": 18, "type": "대중제", "address": "진천군 문백면 농다리로 809"},
  {"name": "젠스필드cc", "region": "충북", "holes": 18, "type": "대중제", "address": "음성군 삼성면 덕호로 382"},
  {"name": "로얄포레cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 신니면 화치3길 35"},
  {"name": "대영힐스cc", "region": "충북", "holes": 27, "type": "대중제", "address": "충주시 대소원면 성종두담길 114"},
  {"name": "진양밸리cc", "region": "충북", "holes": 27, "type": "대중제", "address": "음성군 삼성면 금일로 1195"},
  {"name": "에콜리안제천", "region": "충북", "holes": 9, "type": "대중제", "address": "제천시 고암동 송학 주천로 102"},
  {"name": "코스카cc", "region": "충북", "holes": 27, "type": "대중제", "address": "음성군 음성읍 동음로 318"},
  {"name": "클럽디속리산", "region": "충북", "holes": 18, "type": "대중제", "address": "보은군 탄부면 평각상장로 230"},
  {"name": "동 촌cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 노은면 감노로 1327"},
  {"name": "세 일cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 신니면 동락길 207"},
  {"name": "클럽디보은", "region": "충북", "holes": 18, "type": "대중제", "address": "보은군 보은읍 장속중초로 386"},
  {"name": "올데이 골프앤리조트", "region": "충북", "holes": 27, "type": "대중제", "address": "충주시 앙성면 비내길 189"},
  {"name": "감곡CC", "region": "충북", "holes": 18, "type": "대중제", "address": "음성군 감곡면 문촌리 산81-6"},
  {"name": "일라이트 컨트리클럽", "region": "충북", "holes": 18, "type": "대중제", "address": "영동군 영동읍 매천리 산 35-1"},
  {"name": "일레븐cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 앙성면 본평리 산 43-1"},
  {"name": "킹스데일cc", "region": "충북", "holes": 18, "type": "대중제", "address": "충주시 주덕면 기업도시3로 2"},
  {"name": "블랙스톤cc", "region": "충북", "holes": 18, "type": "대중제", "address": "증평군 도안면 벼루재길 334"},
  {"name": "모나크cc", "region": "충북", "holes": 18, "type": "대중제", "address": "음성군 금왕읍 대금로 1851번길 3-14"},
  {"name": "음성 힐데스하임cc", "region": "충북", "holes": 27, "type": "대중제", "address": "음성군 소이면 후미리 산40-4"},
  {"name": "세레니티cc", "region": "충북", "holes": 9, "type": "비회원제", "address": "청주시 서원구 남이면 산막리 산 128"},
];
